### PR TITLE
Feature square selection

### PR DESCRIPTION
**Pull request by MichaelMrt03**
You can now select a square on the board and it will output the picked board x: and y:

Fixed a mistake with $chessboard to $this->chessboard

Instead of $POST we use $SESSION now make things simpler

There are some problems too:

- Pawn images aren't centered anymore 
- output order is messed up again with inputs on top of the board because of the post action having to be in a big <form> tag to sent all the data

### CODE REVIEW

**Comment by MichaelMrt03** [comment]
> output order is messed up again with inputs on top of the board because of the post action having to be in a big tag to sent all the data

We can also make 2 seperate forms.

1. input with text form
2. input with ui form

Then we just have to make sure that both ui and input option sent the chessboard. I didn't think about that earlier.

**Comment by MichaelMrt03** [comment]
fixed the pawn moves

**Review by ProfNorm — DISMISSED** [review]
I solved the prblem with the pawns not being centered. 
I did not understand what you mean by the second problem you emntioned because everything is working fine for me (inputs below the board etc.)

**Comment by MichaelMrt03** [comment]
> I solved the prblem with the pawns not being centered. 
> 
> I did not understand what you mean by the second problem you emntioned because everything is working fine for me (inputs below the board etc.)

I solved it in the commit "swapped output order" 
@ProfNorm

**Comment by MichaelMrt03** [comment]
Your commit also contains bishop, is this wanted?

**Review by ProfNorm — APPROVED** [review]

**Comment by MichaelMrt03** [comment]
base for #30

**Pull request merged**
